[package]
name = "yamato_event_analyzer"
version = "0.1.0"
authors = ["akiranishikawa <nishikawa@kagosec.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
evtx = { git = "https://github.com/omerbenamram/evtx.git" }
quick-xml = {version = "0.17", features = ["serialize"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0"}
serde_derive = "1.0"
clap = "*"
regex = "1"
csv = "1.1"
base64 = "*"
flate2 = "1.0"
toml = "0.5"
lazy_static = "1.4.0"
chrono = "0.4.19"

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"

[target.i686-pc-windows-gnu]
linker = "i686-w64-mingw32-gcc"
